services:
    db:
        image: postgres:14.5
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=google_drive_tg_bot_user
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app
        command: bash -c "alembic upgrade head && python bot_startup.py"
        env_file:
            - .env
        depends_on:
            - db
        ports:
            - 8080:8080

volumes:
    postgres_data: