"""Final models

Revision ID: a2181a7909d5
Revises: 
Create Date: 2023-05-29 21:52:22.997858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a2181a7909d5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=255), nullable=True),
        sa.Column("original_language", sa.String(length=5), nullable=True),
        sa.Column("popularity", sa.Float(precision=5, asdecimal=True), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("vote_average", sa.Float(precision=7, asdecimal=True), nullable=True),
        sa.Column("genres", sa.Text(), nullable=True),
        sa.Column("cast", sa.Text(), nullable=True),
        sa.Column("directors", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("movie_id"),
    )
    op.create_table(
        "userinfo",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("message_text", sa.Text(), nullable=True),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("from_bot", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["userinfo.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movieuser",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movie.movie_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["userinfo.user_id"],
        ),
        sa.PrimaryKeyConstraint("movie_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movieuser")
    op.drop_table("message")
    op.drop_table("userinfo")
    op.drop_table("movie")
    # ### end Alembic commands ###
